/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package MainFiles;

import static MainFiles.IndexPage.employee;
import db.ConnectSql;
import functions.ValidateFields;
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.HeadlessException;
import java.awt.RenderingHints;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ravindu
 */
public class Employee extends javax.swing.JInternalFrame {

    private final String select = "--Select--";
    /**
     * This will be used to split Code from Description.
     *
     * Represent the Value "--Select--"
     */
    private final String spliter = "--";
    private final DefaultTableModel model_CustomerTable;
    private final String projectPath = System.getProperty("user.dir");

    public Employee() {
        initComponents();
        model_CustomerTable = (DefaultTableModel) tableViewDetails.getModel();
//        loadStaffMembers();
//        loadDepartments();
        rBtnCode.setSelected(true);

//        ImageIcon DefaultBackGround = new ImageIcon(projectPath + "/pictures/InternalFrameIcons/DataFiles/Customer.png");
//
//        ImageIcon internalBackGround = new ImageIcon(projectPath + "/pictures/DefaultBackgrounds/InternalFrames/GrayGradient.png");
//        backgroundLabel.setIcon(internalBackGround);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        panel1 = new javax.swing.JPanel();
        JPanel panel1 = new JPanel() {
            @Override
            protected void paintComponent(Graphics grphcs) {
                super.paintComponent(grphcs);
                Color color1 = Color.white;
                Color color2 = Color.GREEN;
                Graphics2D g2d = (Graphics2D) grphcs;
                g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING,
                    RenderingHints.VALUE_ANTIALIAS_ON);
                GradientPaint gp = new GradientPaint(0, 473,
                    color1.brighter().brighter().brighter(), getWidth(), getHeight(),
                    color2.darker());
                g2d.setPaint(gp);
                g2d.fillRect(0, 473, getWidth(), getHeight());
            }
        };
        lbl_category = new javax.swing.JLabel();
        txtStaffMemCode = new javax.swing.JTextField();
        txtFirstName = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        lbl_description = new javax.swing.JLabel();
        lbl_subAccount = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        rBtnCode = new javax.swing.JRadioButton();
        rBtnName = new javax.swing.JRadioButton();
        lbl_accountType = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableViewDetails = new javax.swing.JTable();
        txtSearch = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        txtSurName = new javax.swing.JTextField();
        txtNameWithIni = new javax.swing.JTextField();
        lbl_accountType2 = new javax.swing.JLabel();
        lbl_accountType3 = new javax.swing.JLabel();
        lbl_accountType4 = new javax.swing.JLabel();
        lbl_accountType5 = new javax.swing.JLabel();
        txtContactLand = new javax.swing.JTextField();
        txtContactMobile = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        lbl_accountType6 = new javax.swing.JLabel();
        Fax = new javax.swing.JLabel();
        lbl_description1 = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        cmbDepartment = new javax.swing.JComboBox();
        cmbDesignation = new javax.swing.JComboBox();
        cmbActive = new javax.swing.JComboBox();
        lbl_accountType7 = new javax.swing.JLabel();
        Fax1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();

        setIconifiable(true);
        setTitle("Employee");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameIconified(evt);
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        panel1.setBackground(new java.awt.Color(255, 255, 255));
        panel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.TRAILING, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 14), new java.awt.Color(153, 153, 153))); // NOI18N
        panel1.setForeground(new java.awt.Color(255, 255, 255));
        panel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel1MouseClicked(evt);
            }
        });
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_category.setForeground(new java.awt.Color(102, 102, 102));
        lbl_category.setText("Employee code");
        panel1.add(lbl_category, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 60, 90, 20));

        txtStaffMemCode.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtStaffMemCodeFocusGained(evt);
            }
        });
        txtStaffMemCode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtStaffMemCodeKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtStaffMemCodeKeyReleased(evt);
            }
        });
        panel1.add(txtStaffMemCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 60, 210, 20));

        txtFirstName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFirstNameFocusGained(evt);
            }
        });
        txtFirstName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFirstNameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFirstNameKeyReleased(evt);
            }
        });
        panel1.add(txtFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 100, 120, 20));

        btnSave.setMnemonic('s');
        btnSave.setText("Save");
        btnSave.setActionCommand("Delete");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        btnSave.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnSaveKeyPressed(evt);
            }
        });
        panel1.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 490, 80, -1));

        btnDelete.setMnemonic('d');
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        btnDelete.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnDeleteKeyPressed(evt);
            }
        });
        panel1.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 490, 80, -1));

        lbl_description.setForeground(new java.awt.Color(102, 102, 102));
        lbl_description.setText("Last name *");
        panel1.add(lbl_description, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 100, 60, 20));

        lbl_subAccount.setForeground(new java.awt.Color(102, 102, 102));
        lbl_subAccount.setText("Search employee by");
        panel1.add(lbl_subAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 140, 20));

        btnExit.setMnemonic('e');
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        btnExit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnExitKeyPressed(evt);
            }
        });
        panel1.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 490, 80, -1));

        rBtnCode.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rBtnCode);
        rBtnCode.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        rBtnCode.setText("Code");
        rBtnCode.setOpaque(false);
        rBtnCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBtnCodeActionPerformed(evt);
            }
        });
        panel1.add(rBtnCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 60, -1));

        rBtnName.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rBtnName);
        rBtnName.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        rBtnName.setText("Name");
        rBtnName.setOpaque(false);
        rBtnName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBtnNameActionPerformed(evt);
            }
        });
        rBtnName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                rBtnNameKeyPressed(evt);
            }
        });
        panel1.add(rBtnName, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 60, -1));

        lbl_accountType.setForeground(new java.awt.Color(102, 102, 102));
        lbl_accountType.setText("Active *");
        panel1.add(lbl_accountType, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 420, 90, 20));

        tableViewDetails.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 0), 1, true));
        tableViewDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employee Code", "First Name", "Sub department"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableViewDetails.getTableHeader().setReorderingAllowed(false);
        tableViewDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableViewDetailsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableViewDetails);

        panel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, 450));

        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });
        panel1.add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 170, -1));
        panel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 468, 440, -1));
        panel1.add(txtSurName, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 140, 120, -1));
        panel1.add(txtNameWithIni, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 140, 130, -1));

        lbl_accountType2.setForeground(new java.awt.Color(102, 102, 102));
        lbl_accountType2.setText("Sur name *");
        panel1.add(lbl_accountType2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, 90, 20));

        lbl_accountType3.setForeground(new java.awt.Color(102, 102, 102));
        lbl_accountType3.setText("Department *");
        panel1.add(lbl_accountType3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 220, 90, 20));

        lbl_accountType4.setForeground(new java.awt.Color(102, 102, 102));
        lbl_accountType4.setText("Contact land");
        panel1.add(lbl_accountType4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 340, 90, 20));

        lbl_accountType5.setForeground(new java.awt.Color(102, 102, 102));
        lbl_accountType5.setText("Contact mobile");
        panel1.add(lbl_accountType5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 380, 90, 20));
        panel1.add(txtContactLand, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 340, 120, -1));
        panel1.add(txtContactMobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 380, 120, -1));
        panel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 180, 120, -1));

        lbl_accountType6.setForeground(new java.awt.Color(102, 102, 102));
        lbl_accountType6.setText("Call name *");
        panel1.add(lbl_accountType6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 180, 80, 20));

        Fax.setForeground(new java.awt.Color(102, 102, 102));
        Fax.setText("Type *");
        panel1.add(Fax, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 300, 80, 20));

        lbl_description1.setForeground(new java.awt.Color(102, 102, 102));
        lbl_description1.setText("First name *");
        panel1.add(lbl_description1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 100, 90, 20));
        panel1.add(txtLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 100, 130, -1));

        cmbDepartment.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Select--" }));
        panel1.add(cmbDepartment, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 220, 220, -1));

        cmbDesignation.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Select--" }));
        panel1.add(cmbDesignation, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 260, 220, -1));

        cmbActive.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Yes", "No" }));
        panel1.add(cmbActive, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 420, 120, -1));

        lbl_accountType7.setForeground(new java.awt.Color(102, 102, 102));
        lbl_accountType7.setText("Initials *");
        panel1.add(lbl_accountType7, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 140, 60, 20));

        Fax1.setForeground(new java.awt.Color(102, 102, 102));
        Fax1.setText("Sub department *");
        panel1.add(Fax1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 260, 90, 20));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Intern", "Probation", "Contract", "Permenent" }));
        panel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 300, 120, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 968, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadDepartments() {
        try {
            java.sql.Statement stmt = ConnectSql.conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
            String query = "select DEPARTMENT_CODE, DEPARTMENT_NAME From departments order by DEPARTMENT_NAME";
            ResultSet rset = stmt.executeQuery(query);

            cmbDepartment.removeAllItems();
            cmbDepartment.insertItemAt("--Select--", 0);
            int position = 1;
            if (rset.next()) {
                do {
                    cmbDepartment.insertItemAt(rset.getString("DEPARTMENT_NAME") + "--" + rset.getString("DEPARTMENT_CODE"), position); //
                    position++;
                } while (rset.next());
            }
            cmbDepartment.setSelectedIndex(0);

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", ERROR);
        }
    }

    private void txtStaffMemCodeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtStaffMemCodeFocusGained
        txtStaffMemCode.selectAll();
    }//GEN-LAST:event_txtStaffMemCodeFocusGained

    private void txtStaffMemCodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStaffMemCodeKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String text = txtStaffMemCode.getText();
            if (!text.isEmpty()) {
                txtFirstName.requestFocus();
                //                LoadAtCodes();
            }
        }
    }//GEN-LAST:event_txtStaffMemCodeKeyPressed

    private void txtStaffMemCodeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStaffMemCodeKeyReleased
        ValidateFields.CheckForCodes(txtStaffMemCode);
    }//GEN-LAST:event_txtStaffMemCodeKeyReleased

    private void txtFirstNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFirstNameFocusGained
        txtFirstName.selectAll();
    }//GEN-LAST:event_txtFirstNameFocusGained

    private void txtFirstNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFirstNameKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String text = txtFirstName.getText();
            if (!text.isEmpty()) {
                txtSurName.requestFocus();
            }
        }
    }//GEN-LAST:event_txtFirstNameKeyPressed

    private void txtFirstNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFirstNameKeyReleased
        ValidateFields.CheckForOtherFields(txtFirstName);
    }//GEN-LAST:event_txtFirstNameKeyReleased

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        CheckBeforeSave();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnSaveKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnSaveKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            CheckBeforeSave();
        }
    }//GEN-LAST:event_btnSaveKeyPressed

    private void CheckBeforeSave() {
        String Code, FirstName, LastName, SurName, NameWithIni, ContactLand,
                ContactMobile, Email, IS_ACTIVE, DESIGNATION, password = "123";

        Code = txtStaffMemCode.getText().toUpperCase();
        FirstName = txtFirstName.getText();
        LastName = txtLastName.getText();
        SurName = txtSurName.getText();
        NameWithIni = txtNameWithIni.getText();
        String department[] = cmbDepartment.getSelectedItem().toString().split("--");
        String checkDepartment = cmbDepartment.getSelectedItem().toString();
        Email = txtEmail.getText();
        ContactLand = txtContactLand.getText();
        ContactMobile = txtContactMobile.getText();
        DESIGNATION = cmbDesignation.getSelectedItem().toString();
        IS_ACTIVE = cmbActive.getSelectedItem().toString();

        if (!Code.isEmpty() && !FirstName.isEmpty() && !SurName.isEmpty() && !Email.isEmpty() && !checkDepartment.equals(select)) {
            try {
                java.sql.Statement stmt = ConnectSql.conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
                java.sql.Statement stmtForUserLogin = ConnectSql.conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
                String query = "select MEMBER_ID From staff_members where MEMBER_ID = '" + Code + "'";
                ResultSet rset = stmt.executeQuery(query);

                if (rset.next()) {
                    int x = JOptionPane.showConfirmDialog(this, "Are you sure to change the '" + Code + "' staff members details?", "Update staff members?", JOptionPane.YES_NO_OPTION);
                    if (x == JOptionPane.YES_OPTION) {
                        String UpdateQuery = "UPDATE staff_members\n"
                                + "   SET \n"
                                + "      MEMBER_FIRST_NAME = '" + FirstName + "'\n"
                                + "      ,MEMBER_LAST_NAME = '" + LastName + "'\n"
                                + "      ,MEMBER_SUR_NAME = '" + SurName + "'\n"
                                + "      ,MEMBER_NAME_INITIAL = '" + NameWithIni + "'\n"
                                + "      ,EMAIL = '" + Email + "'\n"
                                + "      ,CONTACT_LAND = '" + ContactLand + "'\n"
                                + "      ,CONTACT_MOBILE = '" + ContactMobile + "'\n"
                                + "      ,DESIGNATION = '" + DESIGNATION + "'\n"
                                + "      ,IS_ACTIVE = '" + IS_ACTIVE + "'\n"
                                + "      ,departments_DEPARTMENT_CODE = '" + department[1] + "'\n"
                                + " WHERE MEMBER_ID = '" + Code + "'";
                        stmt.execute(UpdateQuery);
                        JOptionPane.showMessageDialog(this, "staff members details are updated.");
                        Refresh();
                    } else if (x == JOptionPane.NO_OPTION) {
                        txtStaffMemCode.requestFocus();
                    }

                } else if (!rset.next()) {
                    String UpdateQuery = "INSERT INTO staff_members\n"
                            + "           (MEMBER_ID\n"
                            + "           ,MEMBER_FIRST_NAME\n"
                            + "           ,MEMBER_LAST_NAME\n"
                            + "           ,MEMBER_SUR_NAME\n"
                            + "           ,MEMBER_NAME_INITIAL\n"
                            + "           ,EMAIL\n"
                            + "           ,CONTACT_LAND\n"
                            + "           ,CONTACT_MOBILE\n"
                            + "           ,DESIGNATION\n"
                            + "           ,IS_ACTIVE\n"
                            + "           ,departments_DEPARTMENT_CODE)\n"
                            + "     VALUES\n"
                            + "           ('" + Code + "'\n"
                            + "           ,'" + FirstName + "'\n"
                            + "           ,'" + LastName + "'\n"
                            + "           ,'" + SurName + "'\n"
                            + "           ,'" + NameWithIni + "'\n"
                            + "           ,'" + Email + "'\n"
                            + "           ,'" + ContactLand + "'\n"
                            + "           ,'" + ContactMobile + "'\n"
                            + "           ,'" + DESIGNATION + "'\n"
                            + "           ,'" + IS_ACTIVE + "'\n"
                            + "           ,'" + department[1] + "') ";
                    stmt.execute(UpdateQuery);

                    String queryToUserLogin = "INSERT INTO `user_login`\n"
                            + "(`STUDENT_OR_MEMBER_ID`,\n"
                            + "`DEPARTMENT_CODE`,\n"
                            + "`USER_NAME`,\n"
                            + "`USER_PASSWORD`)\n"
                            + "VALUES\n"
                            + "(\n"
                            + "'" + Code + "',\n"
                            + "'" + department[1] + "',\n"
                            + "'" + FirstName + "',\n"
                            + "'" + password + "'\n"
                            + ")";
                    stmtForUserLogin.execute(queryToUserLogin);
                    JOptionPane.showMessageDialog(this, "New staff members is saved.");
                    Refresh();
                }
                rset.close();
            } catch (HeadlessException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                JOptionPane.showMessageDialog(this, "Please contact for support.");
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                JOptionPane.showMessageDialog(this, "Please contact for support.");
            }
        } else if (Code.isEmpty() || FirstName.isEmpty() || SurName.isEmpty() || Email.isEmpty() || checkDepartment.equals(select)) {
            JOptionPane.showMessageDialog(this, "Please fill all fields before save.", "Empty fields", JOptionPane.OK_OPTION);
            txtStaffMemCode.requestFocus();
        }
    }

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        CheckBeforeDelete();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnDeleteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnDeleteKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            CheckBeforeDelete();
        }
    }//GEN-LAST:event_btnDeleteKeyPressed

    private void CheckBeforeDelete() {
        String Code = txtStaffMemCode.getText();
        if (!Code.isEmpty()) {
            try {
                java.sql.Statement stmt = ConnectSql.conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
                String query = "select MEMBER_ID From staff_members where MEMBER_ID = '" + Code + "'";
                ResultSet rset = stmt.executeQuery(query);

                if (rset.next()) {
                    Delete();
                } else if (!rset.next()) {
                    JOptionPane.showMessageDialog(this, "Invalid staff members code. Please insert a valid staff members code.", "Invalid staff members code", JOptionPane.OK_OPTION);
                    txtStaffMemCode.requestFocus();
                }

            } catch (HeadlessException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                JOptionPane.showMessageDialog(this, "Please contact for support.");
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                JOptionPane.showMessageDialog(this, "Please contact for support.");
            }
        } else if (Code.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please insert a valid staff members code before delete.", "Empty staff members code", JOptionPane.OK_OPTION);
            txtStaffMemCode.requestFocus();
        }
    }

    private void Delete() {
        String Code = txtStaffMemCode.getText();
        int x = JOptionPane.showConfirmDialog(this, "Are you sure To delete this?", "Delete staff members?", JOptionPane.YES_NO_OPTION);
        if (x == JOptionPane.YES_OPTION) {
            try {
                java.sql.Statement stmt = ConnectSql.conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
                String query = "delete From staff_members where MEMBER_ID = '" + Code + "'";
                stmt.execute(query);
                JOptionPane.showMessageDialog(this, "Staff members is deleted.");
                Refresh();
            } catch (HeadlessException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                JOptionPane.showMessageDialog(this, "Please contact for support.");
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                JOptionPane.showMessageDialog(this, "Please contact for support.");
            }

        } else if (x == JOptionPane.NO_OPTION) {
            txtStaffMemCode.requestFocus();
        }
    }

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        exit();
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnExitKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnExitKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            exit();
        }
    }//GEN-LAST:event_btnExitKeyPressed

    private void exit() {
        if (employee != null) {
            employee = null;
        }
        this.dispose();
    }

    private void rBtnCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBtnCodeActionPerformed
        if (rBtnCode.isSelected()) {
            txtSearch.requestFocus();
            txtSearch.selectAll();
        }
    }//GEN-LAST:event_rBtnCodeActionPerformed

    private void rBtnNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBtnNameActionPerformed
        if (rBtnName.isSelected()) {
            txtSearch.requestFocus();
            txtSearch.selectAll();
        }
    }//GEN-LAST:event_rBtnNameActionPerformed

    private void rBtnNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rBtnNameKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_UP) {
            rBtnCode.requestFocus();
        }
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            rBtnName.setSelected(true);
            btnSave.requestFocus();
        }
    }//GEN-LAST:event_rBtnNameKeyPressed

    private void tableViewDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableViewDetailsMouseClicked
        String Code, FirstName, LastName = "", SurName = "", NameWithIni = "", ContactLand = "",
                ContactMobile = "", Email = "", IS_ACTIVE = "", DESIGNATION = "", departmentCode, departmentName = "";

        Code = tableViewDetails.getValueAt(tableViewDetails.getSelectedRow(), 0).toString();
        FirstName = tableViewDetails.getValueAt(tableViewDetails.getSelectedRow(), 1).toString();
        departmentCode = tableViewDetails.getValueAt(tableViewDetails.getSelectedRow(), 2).toString();

        try {
            ResultSet reset;
            Statement stmt;
            String query;
            query = "SELECT\n"
                    + "     staff_members.`MEMBER_ID` AS staff_members_MEMBER_ID,\n"
                    + "     staff_members.`MEMBER_FIRST_NAME` AS staff_members_MEMBER_FIRST_NAME,\n"
                    + "     staff_members.`MEMBER_LAST_NAME` AS staff_members_MEMBER_LAST_NAME,\n"
                    + "     staff_members.`MEMBER_SUR_NAME` AS staff_members_MEMBER_SUR_NAME,\n"
                    + "     staff_members.`MEMBER_NAME_INITIAL` AS staff_members_MEMBER_NAME_INITIAL,\n"
                    //                    + "     staff_members.`DEPARTMENT_CODE` AS staff_members_DEPARTMENT_CODE,\n"
                    + "     staff_members.`EMAIL` AS staff_members_EMAIL,\n"
                    + "     staff_members.`CONTACT_LAND` AS staff_members_CONTACT_LAND,\n"
                    + "     staff_members.`CONTACT_MOBILE` AS staff_members_CONTACT_MOBILE,\n"
                    + "     staff_members.`DESIGNATION` AS staff_members_DESIGNATION,\n"
                    + "     staff_members.`IS_ACTIVE` AS staff_members_IS_ACTIVE,\n"
                    + "     staff_members.`departments_DEPARTMENT_CODE` AS staff_members_departments_DEPARTMENT_CODE,\n"
                    + "     departments.`DEPARTMENT_CODE` AS departments_DEPARTMENT_CODE,\n"
                    + "     departments.`DEPARTMENT_NAME` AS departments_DEPARTMENT_NAME\n"
                    + "FROM\n"
                    + "     `departments` departments INNER JOIN `staff_members` staff_members ON departments.`DEPARTMENT_CODE` = staff_members.`departments_DEPARTMENT_CODE`\n"
                    + "WHERE staff_members.`MEMBER_ID` = '" + Code + "'";
            stmt = ConnectSql.conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
            reset = stmt.executeQuery(query);

            if (reset.next()) {
                LastName = reset.getString("staff_members_MEMBER_LAST_NAME");
                SurName = reset.getString("staff_members_MEMBER_SUR_NAME");
                NameWithIni = reset.getString("staff_members_MEMBER_NAME_INITIAL");
                departmentName = reset.getString("departments_DEPARTMENT_NAME");
                Email = reset.getString("staff_members_EMAIL");
                ContactLand = reset.getString("staff_members_CONTACT_LAND");
                ContactMobile = reset.getString("staff_members_CONTACT_MOBILE");
                DESIGNATION = reset.getString("staff_members_DESIGNATION");
                IS_ACTIVE = reset.getString("staff_members_IS_ACTIVE");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            JOptionPane.showMessageDialog(this, "Please contact for support.");
        }

        txtStaffMemCode.setText(Code);
        txtFirstName.setText(FirstName);
        txtLastName.setText(LastName);
        txtSurName.setText(SurName);
        txtNameWithIni.setText(NameWithIni);
        cmbDepartment.setSelectedItem(departmentName + "--" + departmentCode);
        txtEmail.setText(Email);
        txtContactLand.setText(ContactLand);
        txtContactMobile.setText(ContactMobile);
        cmbDesignation.setSelectedItem(DESIGNATION);
        cmbActive.setSelectedItem(IS_ACTIVE);
    }//GEN-LAST:event_tableViewDetailsMouseClicked

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        if (rBtnCode.isSelected()) {
            SearchStaffMembersByCode(txtSearch.getText());
        } else if (rBtnName.isSelected()) {
            SearchStaffMembersByName(txtSearch.getText());
        }
    }//GEN-LAST:event_txtSearchKeyReleased

    private void SearchStaffMembersByCode(String CategoryCode) {
        try {
            ResultSet reset;
            Statement stmt;
            String query;
            int rowCount = 0;
            RefreshTable();

            if (!CategoryCode.equals("")) {
                query = "SELECT * FROM staff_members WHERE MEMBER_ID LIKE '" + CategoryCode + "%'";
            } else {
                query = "SELECT * FROM staff_members WHERE MEMBER_ID LIKE '" + CategoryCode + "%'";
            }
            stmt = ConnectSql.conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
            reset = stmt.executeQuery(query);

            while (reset.next()) {

                model_CustomerTable.addRow(new Object[model_CustomerTable.getColumnCount()]);
                tableViewDetails.setValueAt(reset.getString("MEMBER_ID"), rowCount, 0);
                tableViewDetails.setValueAt(reset.getString("MEMBER_FIRST_NAME"), rowCount, 1);
                tableViewDetails.setValueAt(reset.getString("departments_DEPARTMENT_CODE"), rowCount, 2);
                rowCount++;
            }
            reset.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            JOptionPane.showMessageDialog(this, "Please contact for support.");
        }
    }

    private void SearchStaffMembersByName(String CategoryName) {
        try {
            ResultSet reset;
            Statement stmt;
            String query;
            int rowCount = 0;
            RefreshTable();

            if (!CategoryName.equals("")) {
                query = "SELECT * FROM staff_members WHERE MEMBER_FIRST_NAME LIKE '" + CategoryName + "%'";
            } else {
                query = "SELECT * FROM staff_members WHERE MEMBER_FIRST_NAME LIKE '" + CategoryName + "%'";
            }
            stmt = ConnectSql.conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
            reset = stmt.executeQuery(query);

            while (reset.next()) {

                model_CustomerTable.addRow(new Object[model_CustomerTable.getColumnCount()]);
                tableViewDetails.setValueAt(reset.getString("MEMBER_ID"), rowCount, 0);
                tableViewDetails.setValueAt(reset.getString("MEMBER_FIRST_NAME"), rowCount, 1);
                tableViewDetails.setValueAt(reset.getString("departments_DEPARTMENT_CODE"), rowCount, 2);
                rowCount++;
            }
            reset.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            JOptionPane.showMessageDialog(this, "Please contact for support.");
        }
    }

    private void RefreshTable() {
        try {
            int row = model_CustomerTable.getRowCount();
            for (int j = 0; j < row; j++) {
                model_CustomerTable.removeRow(0);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            JOptionPane.showMessageDialog(this, "Please contact for support.");
        }
    }

    private void Refresh() {
        RefreshTableAndLoadAgain();
        txtStaffMemCode.setText("");
        txtFirstName.setText("");
        txtLastName.setText("");
        txtSurName.setText("");
        txtNameWithIni.setText("");
        txtContactLand.setText("");
        txtContactMobile.setText("");
        txtEmail.setText("");
        txtSearch.setText("");

        cmbActive.setSelectedIndex(0);
        cmbDepartment.setSelectedIndex(0);
        cmbDesignation.setSelectedIndex(0);
    }

    private void RefreshTableAndLoadAgain() {
        try {
            int row = model_CustomerTable.getRowCount();
            for (int j = 0; j < row; j++) {
                model_CustomerTable.removeRow(0);
            }
            loadStaffMembers();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            JOptionPane.showMessageDialog(this, "Please contact for support.");
        }
    }

    private void loadStaffMembers() {
        try {
            ResultSet reset;
            Statement stmt;
            String query;
            int rowCount = 0;
            query = "SELECT MEMBER_ID, MEMBER_FIRST_NAME, departments_DEPARTMENT_CODE FROM staff_members ORDER BY MEMBER_FIRST_NAME";
            stmt = ConnectSql.conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
            reset = stmt.executeQuery(query);

            while (reset.next()) {
                model_CustomerTable.addRow(new Object[model_CustomerTable.getColumnCount()]);
                tableViewDetails.setValueAt(reset.getString("MEMBER_ID"), rowCount, 0);
                tableViewDetails.setValueAt(reset.getString("MEMBER_FIRST_NAME"), rowCount, 1);
                tableViewDetails.setValueAt(reset.getString("departments_DEPARTMENT_CODE"), rowCount, 2);
                rowCount++;
            }
            reset.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            JOptionPane.showMessageDialog(this, "Please contact for support.");
        }
    }

    private void panel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel1MouseClicked
        if (SwingUtilities.isRightMouseButton(evt) || evt.isControlDown()) {
            Refresh();
        }
//        int x = evt.getX();
//        int y = evt.getY();
//        System.out.println(x + "," + y);
    }//GEN-LAST:event_panel1MouseClicked

    private void formInternalFrameIconified(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameIconified
        employee.toFront();
    }//GEN-LAST:event_formInternalFrameIconified

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fax;
    private javax.swing.JLabel Fax1;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnSave;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cmbActive;
    private javax.swing.JComboBox cmbDepartment;
    private javax.swing.JComboBox cmbDesignation;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl_accountType;
    private javax.swing.JLabel lbl_accountType2;
    private javax.swing.JLabel lbl_accountType3;
    private javax.swing.JLabel lbl_accountType4;
    private javax.swing.JLabel lbl_accountType5;
    private javax.swing.JLabel lbl_accountType6;
    private javax.swing.JLabel lbl_accountType7;
    private javax.swing.JLabel lbl_category;
    private javax.swing.JLabel lbl_description;
    private javax.swing.JLabel lbl_description1;
    private javax.swing.JLabel lbl_subAccount;
    private javax.swing.JPanel panel1;
    private javax.swing.JRadioButton rBtnCode;
    private javax.swing.JRadioButton rBtnName;
    private javax.swing.JTable tableViewDetails;
    private javax.swing.JTextField txtContactLand;
    private javax.swing.JTextField txtContactMobile;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtNameWithIni;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtStaffMemCode;
    private javax.swing.JTextField txtSurName;
    // End of variables declaration//GEN-END:variables

}
